  import { Geist, Geist_Mono, Inter} from "next/font/google";
  import "./globals.css";
import { ReduxProvider } from "@/lib/redux/provider";
  const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
  });

  const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
  });

  const inter = Inter({
    variable: "--font-inter",
    subsets: ["latin"],
  });

  export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
  };

  export default function RootLayout({ children }) {
    return (
      <html lang="en">
        <body className={`${inter.variable} container mx-auto`}>
          <ReduxProvider>
            {children}
          </ReduxProvider>
        </body>
      </html>
    );
  }
